# Generated by Django 5.0.1 on 2024-01-21 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organisation_directors', to=settings.AUTH_USER_MODEL, verbose_name='директор')),
                ('employees', models.ManyToManyField(null=True, related_name='organisation_employees', to=settings.AUTH_USER_MODEL, verbose_name='сотрудники')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ('name',),
            },
        ),
    ]
