# Generated by Django 5.0.1 on 2024-01-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_alter_organisation_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='breaks.organisation', verbose_name='Организация'),
        ),
    ]
