# Generated by Django 5.0.1 on 2024-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0005_replacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус смены',
                'verbose_name_plural': 'Статусы смены',
                'ordering': ('sort',),
            },
        ),
    ]
